# Generated by Django 4.2.3 on 2023-07-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.lesson')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
