# Generated by Django 4.2.3 on 2023-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment',
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='course_cost'),
            preserve_default=False,
        ),
    ]
