# Generated by Django 4.2.3 on 2023-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remote_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
