# Generated by Django 4.2.3 on 2023-07-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0003_alter_course_description_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurs.lesson'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='user_name')),
                ('date', models.DateField()),
                ('payment', models.IntegerField()),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer')])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurs.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurs.lesson')),
            ],
        ),
    ]
