# Generated by Django 4.2.3 on 2023-07-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0004_alter_payment_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remote_id',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
